# Generated by Django 4.2 on 2025-12-16 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientdoc', '0002_confirmationdocument_deliverychallan_invoiceitem_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='packedimage',
            name='confirmation',
        ),
        migrations.AddField(
            model_name='packedimage',
            name='confirmation_document',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='packedimage_set', to='clientdoc.confirmationdocument'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='status',
            field=models.CharField(choices=[('DRF', 'Draft'), ('DC', 'Delivery Challan Logged'), ('TRP', 'Transport Logged'), ('FIN', 'Finalized & Emailed')], default='DRF', max_length=3),
        ),
    ]
