# Generated by Django 4.2 on 2025-12-16 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientdoc', '0003_remove_packedimage_confirmation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OurCompanyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('gstin', models.CharField(max_length=15)),
                ('state', models.CharField(default='Karnataka', max_length=50)),
                ('state_code', models.CharField(default='29', max_length=2)),
                ('contact_number', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
            options={
                'verbose_name_plural': 'Our Company Profile (Only One Entry)',
            },
        ),
    ]
