# Generated by Django 4.2 on 2025-12-16 08:48

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('clientdoc', '0004_ourcompanyprofile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ourcompanyprofile',
            options={'verbose_name': 'Our Company Profile (Only One Entry)', 'verbose_name_plural': 'Our Company Profile (Only One Entry)'},
        ),
        migrations.RemoveField(
            model_name='packedimage',
            name='confirmation_document',
        ),
        migrations.AddField(
            model_name='packedimage',
            name='confirmation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clientdoc.confirmationdocument'),
        ),
        migrations.AddField(
            model_name='storelocation',
            name='gstin',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='storelocation',
            name='state',
            field=models.CharField(default='Karnataka', max_length=50),
        ),
        migrations.AddField(
            model_name='storelocation',
            name='state_code',
            field=models.CharField(default='29', max_length=2),
        ),
        migrations.AlterField(
            model_name='confirmationdocument',
            name='approval_email_file',
            field=models.FileField(blank=True, null=True, upload_to='confirmation_docs/email/', verbose_name='Approval Email PDF'),
        ),
        migrations.AlterField(
            model_name='confirmationdocument',
            name='invoice',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='clientdoc.salesinvoice'),
        ),
        migrations.AlterField(
            model_name='confirmationdocument',
            name='po_file',
            field=models.FileField(blank=True, null=True, upload_to='confirmation_docs/po/', verbose_name='PO Copy'),
        ),
        migrations.AlterField(
            model_name='deliverychallan',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='deliverychallan',
            name='invoice',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='clientdoc.salesinvoice'),
        ),
        migrations.AlterField(
            model_name='deliverychallan',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clientdoc.item'),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='ourcompanyprofile',
            name='contact_number',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='ourcompanyprofile',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='ourcompanyprofile',
            name='gstin',
            field=models.CharField(blank=True, default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='ourcompanyprofile',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='salesinvoice',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='salesinvoice',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clientdoc.storelocation'),
        ),
        migrations.AlterField(
            model_name='salesinvoice',
            name='status',
            field=models.CharField(choices=[('DRF', 'Draft (Invoice Created)'), ('DC', 'Delivery Challan Logged'), ('TRP', 'Transport Charges Logged'), ('FIN', 'Finalized (PDF Generated)')], default='DRF', max_length=3),
        ),
        migrations.AlterField(
            model_name='salesinvoice',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='storelocation',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='transportcharges',
            name='charges',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='transportcharges',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='transportcharges',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transportcharges',
            name='invoice',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='clientdoc.salesinvoice'),
        ),
    ]
