# Generated by Django 4.2 on 2025-12-16 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientdoc', '0005_alter_ourcompanyprofile_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='packedimage',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Image Notes'),
        ),
    ]
