# Generated by Django 4.2 on 2025-12-16 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientdoc', '0006_packedimage_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesinvoice',
            name='app_invoice_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='App Invoice No.'),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='tally_invoice_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Tally Invoice No.'),
        ),
    ]
