# Generated by Django 4.2 on 2025-12-16 11:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('clientdoc', '0007_salesinvoice_app_invoice_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='confirmationdocument',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
