# Generated by Django 4.2.23 on 2025-12-16 14:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('clientdoc', '0008_confirmationdocument_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='hsn_sac',
            field=models.CharField(default='844311', max_length=20, verbose_name='HSN/SAC'),
        ),
        migrations.AddField(
            model_name='ourcompanyprofile',
            name='account_holder_name',
            field=models.CharField(default='Transcend Digital Solutions', max_length=100),
        ),
        migrations.AddField(
            model_name='ourcompanyprofile',
            name='account_number',
            field=models.CharField(default='89440200002020', max_length=50),
        ),
        migrations.AddField(
            model_name='ourcompanyprofile',
            name='bank_name',
            field=models.CharField(default='BANK OF BARODA', max_length=100),
        ),
        migrations.AddField(
            model_name='ourcompanyprofile',
            name='branch_name',
            field=models.CharField(default='ULSOOR', max_length=100),
        ),
        migrations.AddField(
            model_name='ourcompanyprofile',
            name='ifsc_code',
            field=models.CharField(default='BARB0VJULSO', max_length=20),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='amount_in_words',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='buyers_order_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name="Buyer's Order Date"),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='buyers_order_no',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name="Buyer's Order No."),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='delivery_note',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='delivery_note_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Delivery Note Date'),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='destination',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='dispatch_doc_no',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Dispatch Doc No.'),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='dispatched_through',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Dispatched through'),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='mode_terms_payment',
            field=models.CharField(default='30 Days', max_length=100, verbose_name='Mode/Terms of Payment'),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='other_references',
            field=models.CharField(default='EMAIL Approval', max_length=100),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='reference_no_date',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Reference No. & Date'),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='tax_amount_in_words',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='terms_of_delivery',
            field=models.TextField(blank=True, null=True),
        ),
    ]
