# Generated by Django 4.2.27 on 2025-12-17 03:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('clientdoc', '0010_activitylog_confirmationdocument_is_deleted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='confirmationdocument',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='deliverychallan',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='transportcharges',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
