# Generated by Django 4.2.23 on 2025-12-18 03:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientdoc', '0011_confirmationdocument_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('address', models.TextField()),
                ('gstin', models.CharField(blank=True, max_length=15, null=True)),
                ('state', models.CharField(choices=[('Karnataka', 'Karnataka (29)'), ('Maharashtra', 'Maharashtra (27)'), ('Tamil Nadu', 'Tamil Nadu (33)'), ('Kerala', 'Kerala (32)'), ('Andhra Pradesh', 'Andhra Pradesh (37)'), ('Telangana', 'Telangana (36)'), ('Delhi', 'Delhi (07)'), ('Uttar Pradesh', 'Uttar Pradesh (09)'), ('Gujarat', 'Gujarat (24)'), ('Rajasthan', 'Rajasthan (08)'), ('West Bengal', 'West Bengal (19)'), ('Punjab', 'Punjab (03)'), ('Haryana', 'Haryana (06)'), ('Madhya Pradesh', 'Madhya Pradesh (23)'), ('Bihar', 'Bihar (10)'), ('Odisha', 'Odisha (21)'), ('Assam', 'Assam (18)'), ('Other', 'Other')], default='Karnataka', max_length=50)),
                ('state_code', models.CharField(default='29', max_length=2)),
                ('pincode', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ItemCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Item Categories',
            },
        ),
        migrations.AddField(
            model_name='item',
            name='article_code',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Article/SKU'),
        ),
        migrations.AddField(
            model_name='item',
            name='gst_rate',
            field=models.DecimalField(decimal_places=2, default=0.18, max_digits=5, verbose_name='GST Rate (Decimal)'),
        ),
        migrations.AddField(
            model_name='ourcompanyprofile',
            name='signature',
            field=models.ImageField(blank=True, help_text='Upload signature image for PDFs', null=True, upload_to='company_signatures/'),
        ),
        migrations.AddField(
            model_name='storelocation',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='storelocation',
            name='pincode',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='storelocation',
            name='priority',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Priority (P1-P4)'),
        ),
        migrations.AddField(
            model_name='storelocation',
            name='site_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Item Name/Particular'),
        ),
        migrations.AlterField(
            model_name='salesinvoice',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clientdoc.storelocation', verbose_name='Location (Ship To/Consignee)'),
        ),
        migrations.AlterField(
            model_name='storelocation',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Site Name'),
        ),
        migrations.AlterField(
            model_name='storelocation',
            name='state',
            field=models.CharField(choices=[('Karnataka', 'Karnataka (29)'), ('Maharashtra', 'Maharashtra (27)'), ('Tamil Nadu', 'Tamil Nadu (33)'), ('Kerala', 'Kerala (32)'), ('Andhra Pradesh', 'Andhra Pradesh (37)'), ('Telangana', 'Telangana (36)'), ('Delhi', 'Delhi (07)'), ('Uttar Pradesh', 'Uttar Pradesh (09)'), ('Gujarat', 'Gujarat (24)'), ('Rajasthan', 'Rajasthan (08)'), ('West Bengal', 'West Bengal (19)'), ('Punjab', 'Punjab (03)'), ('Haryana', 'Haryana (06)'), ('Madhya Pradesh', 'Madhya Pradesh (23)'), ('Bihar', 'Bihar (10)'), ('Odisha', 'Odisha (21)'), ('Assam', 'Assam (18)'), ('Other', 'Other')], default='Karnataka', max_length=50),
        ),
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clientdoc.itemcategory', verbose_name='Category/Details'),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='buyer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='clientdoc.buyer', verbose_name='Buyer (Bill To)'),
        ),
    ]
