# Generated by Django 4.2 on 2025-12-18 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientdoc', '0012_buyer_itemcategory_item_article_code_item_gst_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='item_images/', verbose_name='Product Image'),
        ),
    ]
