# Generated by Django 4.2.23 on 2025-12-18 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientdoc', '0013_item_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceitem',
            name='gst_rate',
            field=models.DecimalField(decimal_places=2, default=0.18, max_digits=5),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
