# Generated by Django 4.2.27 on 2025-12-18 07:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('clientdoc', '0014_invoiceitem_gst_rate_invoiceitem_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceitem',
            name='discount_type',
            field=models.CharField(choices=[('Percentage', 'Percentage (%)'), ('Amount', 'Amount (Fixed)')], default='Percentage', max_length=20),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='discount_value',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='quantity_billed',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='quantity_shipped',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='item',
            name='unit',
            field=models.CharField(default='Nos', max_length=50, verbose_name='Unit (e.g. Nos, Kg)'),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='remark',
            field=models.TextField(blank=True, null=True, verbose_name='Remarks'),
        ),
        migrations.AlterField(
            model_name='salesinvoice',
            name='buyers_order_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name="Buyer's Order Date"),
        ),
        migrations.AlterField(
            model_name='salesinvoice',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='salesinvoice',
            name='delivery_note_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Delivery Note Date'),
        ),
    ]
