# Generated by Django 4.2 on 2025-12-18 07:50

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientdoc', '0015_invoiceitem_discount_type_invoiceitem_discount_value_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='image',
        ),
        migrations.AddField(
            model_name='item',
            name='hsn_code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='HSN Code'),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='cgst_total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='customer_gstin',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='igst_total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='place_of_supply',
            field=models.CharField(blank=True, choices=[('01', 'Jammu & Kashmir (01)'), ('02', 'Himachal Pradesh (02)'), ('03', 'Punjab (03)'), ('04', 'Chandigarh (04)'), ('05', 'Uttarakhand (05)'), ('06', 'Haryana (06)'), ('07', 'Delhi (07)'), ('08', 'Rajasthan (08)'), ('09', 'Uttar Pradesh (09)'), ('10', 'Bihar (10)'), ('11', 'Sikkim (11)'), ('12', 'Arunachal Pradesh (12)'), ('13', 'Nagaland (13)'), ('14', 'Manipur (14)'), ('15', 'Mizoram (15)'), ('16', 'Tripura (16)'), ('17', 'Meghalaya (17)'), ('18', 'Assam (18)'), ('19', 'West Bengal (19)'), ('20', 'Jharkhand (20)'), ('21', 'Odisha (21)'), ('22', 'Chhattisgarh (22)'), ('23', 'Madhya Pradesh (23)'), ('24', 'Gujarat (24)'), ('25', 'Daman & Diu (25)'), ('26', 'Dadra & Nagar Haveli (26)'), ('27', 'Maharashtra (27)'), ('29', 'Karnataka (29)'), ('30', 'Goa (30)'), ('31', 'Lakshadweep (31)'), ('32', 'Kerala (32)'), ('33', 'Tamil Nadu (33)'), ('34', 'Puducherry (34)'), ('35', 'Andaman & Nicobar Islands (35)'), ('36', 'Telangana (36)'), ('37', 'Andhra Pradesh (37)'), ('38', 'Ladakh (38)'), ('97', 'Other Territory (97)')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='sgst_total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
    ]
