# Generated by Django 4.2 on 2025-12-18 08:05

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientdoc', '0016_remove_item_image_item_hsn_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceitem',
            name='gst_rate',
            field=models.DecimalField(choices=[(Decimal('0.00'), '0%'), (Decimal('0.05'), '5%'), (Decimal('0.12'), '12%'), (Decimal('0.18'), '18%'), (Decimal('0.28'), '28%'), (Decimal('0.40'), '40%')], decimal_places=2, default=0.18, max_digits=5),
        ),
        migrations.AlterField(
            model_name='item',
            name='gst_rate',
            field=models.DecimalField(choices=[(Decimal('0.00'), '0%'), (Decimal('0.05'), '5%'), (Decimal('0.12'), '12%'), (Decimal('0.18'), '18%'), (Decimal('0.28'), '28%'), (Decimal('0.40'), '40%')], decimal_places=2, default=0.18, max_digits=5, verbose_name='GST Rate'),
        ),
    ]
