# Generated by Django 4.2 on 2025-12-18 08:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('clientdoc', '0017_alter_invoiceitem_gst_rate_alter_item_gst_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confirmationdocument',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='deliverychallan',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='transportcharges',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
