# Generated by Django 4.2.23 on 2026-01-06 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientdoc', '0018_alter_confirmationdocument_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BulkInvoiceUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='bulk_uploads/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Processed', 'Processed'), ('Failed', 'Failed')], default='Pending', max_length=20)),
                ('log', models.TextField(blank=True, help_text='Log of success/errors during processing', null=True)),
            ],
        ),
    ]
